### ISSUE TITLE
Prepare sticky for release

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/sticky-nav#1]
- add tests 
- make a single file (get rid of require)
- should it export the constructor or assign the element name 
- remove container
- do we want to use selector like this does: https://github.com/bit-docs/bit-docs-html-toc
  - heading-selector="h2"
  - scrollable-container-selector="body"
  - stick = "true"
- Change Navbar to nav
- hard coding what is scrolling 
- listen to resize 
- remove using ids to listen to elements
- remove the `offsetTop -70`.
- header being added inside a form element

## Styling 

- remove outer element

## Testing 

- Create a test page that uses ESModules for now to import the webcomponent and use.
- Write up the major test cases in an issue

## Memory safety 

- Listening to scroll is not torn down.

**Comment by jmlawrence** [comment]
Addressed issues.
